// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function getResult(param) {
  if (Math.random() > 0.5) {
    return "result";
  }
  
}

var result = getResult(undefined);

if (result !== undefined) {
  console.log("Has result");
} else {
  console.log("Cannot get result");
}

exports.getResult = getResult;
exports.result = result;
/* result Not a pure module */
