// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var john = {
  name: "john",
  age: 12,
  job: "student"
};

console.log("His name is " + john.name + ". He is a " + john.job);

var updatedJohn = {
  name: john.name,
  age: john.age + 1 | 0,
  job: john.job
};

john.job = "teacher";

console.log("John's new job is " + john.job);

function getAge(entity) {
  return entity.age;
}

exports.john = john;
exports.updatedJohn = updatedJohn;
exports.getAge = getAge;
/*  Not a pure module */
