// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function add(a, b) {
  return a + b | 0;
}

var myArrOfString = [
  "foo",
  "bar"
];

function subtract(a, b) {
  return a - b | 0;
}

console.log(7);

var myUser = {
  name: "foo",
  age: 12,
  address: "Street 1",
  job: "Teacher"
};

var fetchUserResultSuccess = {
  TAG: /* Ok */0,
  _0: {
    user_id: "123"
  }
};

var john = {
  name: "John",
  friends: []
};

var harry = {
  name: "Harry",
  friends: [john]
};

var gpa = 2.1 + 10;

var score = 10;

var myInt = 10;

var myStr = "10";

var myNumb = 10;

var firstRect = [
  10,
  20
];

var fetchUserFail = {
  TAG: /* Error */1,
  _0: "failed to fetch user data"
};

var age = 10;

exports.score = score;
exports.add = add;
exports.myArrOfString = myArrOfString;
exports.myInt = myInt;
exports.myStr = myStr;
exports.subtract = subtract;
exports.myNumb = myNumb;
exports.myUser = myUser;
exports.firstRect = firstRect;
exports.fetchUserResultSuccess = fetchUserResultSuccess;
exports.fetchUserFail = fetchUserFail;
exports.john = john;
exports.harry = harry;
exports.age = age;
exports.gpa = gpa;
/*  Not a pure module */
