// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function render(color) {
  if (color === "red") {
    console.log("Red");
  } else if (color === "green") {
    console.log("Green");
  } else {
    console.log("Blue");
  }
  
}

render("red");

function printManufacturer(phone) {
  if (phone === "pixel5" || phone === "pixel2") {
    console.log(phone + " is a Google phone");
  } else if (phone === "iPhone7" || phone === "iPhone6" || phone === "iPhone5") {
    console.log(phone + " is an iPhone");
  } else {
    console.log(phone + " is a Samsung phone");
  }
  
}

printManufacturer("iPhone5");

printManufacturer("pixel5");

var redColor = "red";

var foosPhone = "pixel2";

var iPhone5 = "iPhone5";

var pixel5 = "pixel5";

exports.render = render;
exports.redColor = redColor;
exports.foosPhone = foosPhone;
exports.printManufacturer = printManufacturer;
exports.iPhone5 = iPhone5;
exports.pixel5 = pixel5;
/*  Not a pure module */
