// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var successGetUserResponse = {
  TAG: /* Success */0,
  status: 200,
  data: {
    id: "10",
    name: "Foo"
  }
};

var failedGetUserResponse = {
  TAG: /* Error */1,
  status: 404,
  error: "Not found"
};

function handleGetUserResponse(data) {
  if (data.TAG === /* Success */0) {
    console.log("User name is " + data.data.name);
    return ;
  }
  console.log("Failed to get user. Status code: " + String(data.status) + ". Error: " + data.error);
  
}

handleGetUserResponse(successGetUserResponse);

handleGetUserResponse(failedGetUserResponse);

var myResponse = /* Unsure */2;

exports.myResponse = myResponse;
exports.successGetUserResponse = successGetUserResponse;
exports.failedGetUserResponse = failedGetUserResponse;
exports.handleGetUserResponse = handleGetUserResponse;
/*  Not a pure module */
