// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("rescript/lib/js/list.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

function parseData(data) {
  return {
          name: data.name,
          age: data.age
        };
}

function getAge(person) {
  return person.age;
}

function validateAge(age) {
  if (age >= 18) {
    return "over 18 years old";
  } else {
    return "under 18 years old";
  }
}

var john = {
  name: "John",
  age: 20
};

var daniel = {
  name: "Daniel",
  age: 17
};

var people = [
  john,
  daniel
];

function validateAgeThenPrint(person) {
  console.log(person.name + " is " + validateAge(parseData(person).age));
  
}

Belt_Array.forEach(people, validateAgeThenPrint);

function wrappedFilter(list) {
  return List.filter(function (el) {
                return el > 2;
              })(list);
}

var myList = List.rev(wrappedFilter(List.flatten({
              hd: {
                hd: 1,
                tl: {
                  hd: 2,
                  tl: /* [] */0
                }
              },
              tl: {
                hd: {
                  hd: 3,
                  tl: {
                    hd: 5,
                    tl: /* [] */0
                  }
                },
                tl: /* [] */0
              }
            })));

function add(x, y) {
  return x + y | 0;
}

function addThree(__x) {
  return 3 + __x | 0;
}

console.log(5);

var anotherList = List.rev(List.filter(function (el) {
            return el > 2;
          })(List.flatten({
              hd: {
                hd: 1,
                tl: {
                  hd: 2,
                  tl: /* [] */0
                }
              },
              tl: {
                hd: {
                  hd: 3,
                  tl: {
                    hd: 5,
                    tl: /* [] */0
                  }
                },
                tl: /* [] */0
              }
            })));

exports.parseData = parseData;
exports.getAge = getAge;
exports.validateAge = validateAge;
exports.john = john;
exports.daniel = daniel;
exports.people = people;
exports.validateAgeThenPrint = validateAgeThenPrint;
exports.wrappedFilter = wrappedFilter;
exports.myList = myList;
exports.add = add;
exports.addThree = addThree;
exports.anotherList = anotherList;
/*  Not a pure module */
