// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

console.log("I speak " + "Spanish");

function handleResult(result) {
  if (result.TAG === /* Left */0) {
    console.log("Failed to get user. Error: " + result._0);
    return ;
  }
  console.log("Got user: " + result._0.name);
  
}

handleResult({
      TAG: /* Left */0,
      _0: "404"
    });

handleResult({
      TAG: /* Right */1,
      _0: {
        id: "1",
        name: "Foo"
      }
    });

function compute(calcFn, value) {
  return Curry._1(calcFn, value);
}

function add(step, val) {
  return step + val | 0;
}

function addOne(param) {
  return 1 + param | 0;
}

var val = 10;

console.log("Value is " + String(val));

function compose(func1, func2, val) {
  return Curry._1(func1, Curry._1(func2, val));
}

function multiply(step, val) {
  return Math.imul(step, val);
}

function multiplyTwo(param) {
  return (param << 1);
}

function addOneThenMultiplyTwo(param) {
  return ((1 + param | 0) << 1);
}

console.log(true);

exports.handleResult = handleResult;
exports.compute = compute;
exports.add = add;
exports.addOne = addOne;
exports.val = val;
exports.compose = compose;
exports.multiply = multiply;
exports.multiplyTwo = multiplyTwo;
exports.addOneThenMultiplyTwo = addOneThenMultiplyTwo;
/*  Not a pure module */
