// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function multiply(a, b, param) {
  if (b !== undefined) {
    console.log(Math.imul(a, b));
  } else {
    console.log(a);
  }
  
}

console.log("Multiply results:");

multiply(2, 3, undefined);

multiply(4, undefined, undefined);

var payload = 7;

multiply(5, payload, undefined);

function greet(name, additional, param) {
  if (additional !== undefined) {
    console.log("Hello " + name + ". " + additional);
  } else {
    console.log("Hello " + name);
  }
  
}

console.log("Greet results:");

greet("Foo", undefined, undefined);

function sayHi(greetOpt, name, param) {
  var greet = greetOpt !== undefined ? greetOpt : "Hello";
  console.log(greet + " " + name);
  
}

console.log("Say hi results:");

sayHi(undefined, "Foo", undefined);

sayHi("Hi", "Foo", undefined);

var partial_arg = "Hi there";

function partialSayHi(param, param$1) {
  return sayHi(partial_arg, param, param$1);
}

partialSayHi("Bar", undefined);

function partialGreet(param, param$1) {
  return greet("Foo", param, param$1);
}

greet("Foo", "Nice to meet you", undefined);

greet("Bar", "Nice to meet you", undefined);

function add(base, addition) {
  var result = base + addition | 0;
  console.log(result);
  
}

function addOne(param) {
  return add(1, param);
}

console.log("Add results:");

add(1, 3);

exports.multiply = multiply;
exports.payload = payload;
exports.greet = greet;
exports.sayHi = sayHi;
exports.partialSayHi = partialSayHi;
exports.partialGreet = partialGreet;
exports.add = add;
exports.addOne = addOne;
/*  Not a pure module */
