// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("rescript/lib/js/list.js");
var Caml_format = require("rescript/lib/js/caml_format.js");

function toInt(lang, speed) {
  return Caml_format.caml_int_of_string("learn " + lang + speed);
}

function partiallyAppliedFn(param) {
  return toInt("ReScript", param);
}

function concatListsPartial(list1, list2) {
  var newList = List.append(list1, list2);
  return function (list3) {
    return List.append(list3, newList);
  };
}

var partialConcat = concatListsPartial({
      hd: "Orange",
      tl: /* [] */0
    }, {
      hd: "Apple",
      tl: /* [] */0
    });

var finalList = partialConcat({
      hd: "Banana",
      tl: /* [] */0
    });

console.log(finalList);

exports.toInt = toInt;
exports.partiallyAppliedFn = partiallyAppliedFn;
exports.concatListsPartial = concatListsPartial;
exports.partialConcat = partialConcat;
exports.finalList = finalList;
/* partialConcat Not a pure module */
