// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var greeting = "hello";

console.log(greeting);

console.log("foo bar");

console.log("baz");

var message;

var foo = "bar";

exports.greeting = greeting;
exports.message = message;
exports.foo = foo;
/*  Not a pure module */
