// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var greeting = "hello";

console.log(greeting);

console.log("foo bar");

var message;

exports.greeting = greeting;
exports.message = message;
/*  Not a pure module */
